apiVersion: v1
kind: Namespace
metadata:
  name: nexus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-app
  namespace: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
        app: nexus-app
  template:
    metadata:
      labels:
        app: nexus-app
    spec:
      containers:
      - name: nexus
        image: sonatype/nexus3:3.60.0
        resources:
          limits:
            memory: "3Gi"
            cpu: "768m"
          requests:
            memory: "2Gi"
            cpu: "512m"
        ports:
        - containerPort: 8081
        - containerPort: 5000
        volumeMounts:
          - name: nexus-volume
            mountPath: /nexus-data
      volumes:
        - name: nexus-volume
          hostPath:
            path: /nexus
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: nexus
spec:
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP
    name: nexus
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: nexus-registry
  selector:
    app: nexus-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexus-ingress
  namespace: nexus
  annotations:
    ingress.kubernetes.io/proxy-body-size: 100m
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - nexus.constellation.com 
    - registry.constellation.com
    secretName: nexus-tls
  rules:
  - host: nexus.constellation.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          name: nexus-service
          port:
            number: 80
  - host: registry.constellation.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          name: nexus-service
          port:
            number: 5000