apiVersion: v1
kind: Namespace
metadata:
  name: nexus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
        app: nexus-server
  template:
    metadata:
      labels:
        app: nexus-server
    spec:
      containers:
        - name: nexus
          image: sonatype/nexus3:3.60.0
          resources:
            limits:
              memory: "3Gi"
              cpu: "768m"
            requests:
              memory: "2Gi"
              cpu: "512m"
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: nexus-data
              mountPath: /nexus-data
      volumes:
        - name: nexus-data
          hostPath:
            path: /nexus
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: nexus
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8081
  selector:
    app: nexus-server
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nexus
spec:
  rules:
  - host: nexus.constellation.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nexus
            port:
              number: 80