version: '3.9'

services:
  bind9:
    image: ubuntu/bind9:9.18-22.04_beta
    container_name: dns-server
    environment:
      - BIND9_USER=root
      - TZ=Asia/Almaty
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - /dns-server/config:/etc/bind
      - /dns-server/cache:/var/cache/bind
      - /dns-server/records:/var/lib/bind
    restart: on-failure:3
    networks:
      - dns

networks:
  dns:
    name: dns